version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - REACT_APP_NODE_ENV=production
      - REACT_APP_SERVER_BASE_URL=${REACT_APP_SERVER_BASE_URL}
