# backend/docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Add any other environment variables your backend needs
      # - DATABASE_URL=your_database_url
      # - JWT_SECRET=your_jwt_secret

networks:
  app-network:
    driver: bridge