# frontend/docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - REACT_APP_NODE_ENV=production
        - REACT_APP_SERVER_BASE_URL=http://13.61.176.80:5000  # Your AWS backend URL
    ports:
      - "5173:5173"  # Map to the port you're using
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge